- name: Install and configure MariaDB
  hosts: db-mysql
  become: yes

  tasks:
    - name: Install MariaDB server
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Install PyMySQL (required for Ansible MySQL modules)
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Ensure MariaDB service is started and enabled
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Set root password for MariaDB
      community.mysql.mysql_user:
        login_user: root
        login_password: "vprodbpass"
        user: root
        host_all: yes
        password: "vprodbpass"
        state: present

    - name: Remove anonymous users
      community.mysql.mysql_user:
        login_user: root
        login_password: "vprodbpass"
        name: ''
        host_all: yes
        state: absent

    - name: Remove test database
      community.mysql.mysql_db:
        login_user: root
        login_password: "vprodbpass"
        name: test
        state: absent

    - name: Create application database
      community.mysql.mysql_db:
        login_user: root
        login_password: "vprodbpass"
        name: accounts
        state: present

    - name: Create application database user
      community.mysql.mysql_user:
        login_user: root
        login_password: "vprodbpass"
        name: root
        password: "admin123"
        priv: "accounts.*:ALL"
        host: "%"
        state: present

    - name: Copy database backup to server
      ansible.builtin.copy:
        src: "/home/ubuntu/vprofile-project/ansible/db_backup.sql"
        dest: "/tmp/db_backup.sql"
        owner: root
        group: root
        mode: '0644'

    - name: Restore database from backup
      ansible.builtin.shell: |
        mysql -u root -p'vprodbpass' accounts < /tmp/db_backup.sql
      args:
        executable: /bin/bash

    - name: Remove temporary backup file
      ansible.builtin.file:
        path: "/tmp/db_backup.sql"
        state: absent

    - name: Verify MariaDB service is running
      ansible.builtin.shell: systemctl is-active mariadb
      register: mariadb_status
      changed_when: false

    - debug:
        msg: "MariaDB status: {{ mariadb_status.stdout }}"

