---
- name: Install and configure Tomcat 9
  hosts: app-web
  become: yes

  tasks:
    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Create Tomcat user
      user:
        name: tomcat
        shell: /bin/false
        create_home: no

    - name: Download Tomcat 9
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.109/bin/apache-tomcat-9.0.109.tar.gz
        dest: /tmp/tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Rename folder to /opt/tomcat
      command: mv /opt/apache-tomcat-9.0.109 /opt/tomcat
      args:
        removes: /opt/tomcat

    - name: Change ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        state: directory
        recurse: yes

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat 9
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
          Environment="CATALINA_HOME=/opt/tomcat"
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start Tomcat
      systemd:
        daemon_reload: yes
        name: tomcat
        state: started
        enabled: yes

