---
- name: Install and configure Tomcat 9
  hosts: app-web
  become: yes

  vars:
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_home: /opt/tomcat
    tomcat_version: 9.0.109
    war_source: /var/lib/jenkins/workspace/ansible_ci-cd_vprofile/target/vprofile-v2.war
    war_dest: /opt/tomcat/webapps/vprofile-v2.war

  tasks:
    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        shell: /bin/false
        create_home: no

    - name: Download Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /tmp/tomcat.tar.gz

    - name: Check if Tomcat folder exists
      stat:
        path: "{{ tomcat_home }}"
      register: tomcat_stat

    - name: Remove existing Tomcat folder or symlink
      file:
        path: "{{ tomcat_home }}"
        state: absent
      when: tomcat_stat.stat.exists

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Rename extracted folder to /opt/tomcat
      command: mv /opt/apache-tomcat-{{ tomcat_version }} "{{ tomcat_home }}"
      args:
        removes: /opt/apache-tomcat-{{ tomcat_version }}

    - name: Set ownership for Tomcat
      file:
        path: "{{ tomcat_home }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        state: directory
        recurse: yes

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat 9
          After=network.target

          [Service]
          Type=forking
          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          Environment="JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
          Environment="CATALINA_HOME={{ tomcat_home }}"
          ExecStart={{ tomcat_home }}/bin/startup.sh
          ExecStop={{ tomcat_home }}/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start Tomcat
      systemd:
        daemon_reload: yes
        name: tomcat
        state: started
        enabled: yes

    - name: Deploy WAR file from Jenkins workspace
      copy:
        src: "{{ war_source }}"
        dest: "{{ war_dest }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0644'
        remote_src: no   # <--- Important: WAR is on controller

    - name: Restart Tomcat to deploy app
      systemd:
        name: tomcat
        state: restarted

